### ISSUE TITLE
Error while loading rule 'module-resolver/use-alias': Cannot read property 'plugins' of null

### ISSUE THREAD

**Issue by samit4me** [HeroProtagonist/eslint-plugin-module-resolver#15] opened 2019-08-01 23:29 UTC
Using:
```
"@babel/core": "7.4.3",
"babel-plugin-module-resolver": "3.2.0",
"eslint-plugin-module-resolver": "0.13.0",
```

When trying to add `"module-resolver/use-alias": 2` to `.eslintrc` I get the following output from ESLint:
```
TypeError: Error while loading rule 'module-resolver/use-alias': Cannot read property 'plugins' of null
    at Object.create (/path/to/project/packages/web/node_modules/eslint-plugin-module-resolver/dist/rules/use-alias.js:56:40)
    at createRuleListeners (/path/to/project/packages/web/node_modules/eslint/lib/linter.js:577:21)
    at Object.keys.forEach.ruleId (/path/to/project/packages/web/node_modules/eslint/lib/linter.js:731:31)
    at Array.forEach (<anonymous>)
    at runRules (/path/to/project/packages/web/node_modules/eslint/lib/linter.js:689:34)
    at Linter._verifyWithoutProcessors (/path/to/project/packages/web/node_modules/eslint/lib/linter.js:891:31)
    at preprocess.map.textBlock (/path/to/project/packages/web/node_modules/eslint/lib/linter.js:940:35)
    at Array.map (<anonymous>)
    at Linter.verify (/path/to/project/packages/web/node_modules/eslint/lib/linter.js:939:42)
    at Linter.verifyAndFix (/path/to/project/packages/web/node_modules/eslint/lib/linter.js:1032:29)
```

It's worth noting that when running ESLint the rule is actually working.

**Comment by HeroProtagonist** [comment] 2019-08-02 17:39
Hi @samit4me,

Does your repo have a config file for babel? If you can post it or one that represents it and what level of the directory it is in, that would be helpful for debugging

I use [find-babel-config](https://github.com/tleunen/find-babel-config) and it appears that it is not finding one for your project

**Comment by samit4me** [comment] 2019-08-03 03:00
Hi @HeroProtagonist, unfortunately I don't have access to that repo until next week as my workplace does not allow remote access, so I've done up an example repo to replicate the issue.

Demo Repo: https://github.com/samit4me/use-alias-demo

To see the issue:
- ensure you have vscode with the [eslint plugin](https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint) installed,
- checkout the repo,
- npm i
- open vscode at root of project,
- open file `fullPath.js`
- now you should see the error popup in vscode OR see the details in the output (View > Output)

**Findings**
The issue appears to be with the [vscode eslint plugin](https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint) and where `.eslintrc`lives, because:

a) It's working fine from the command line
b) If I move all the code up to the root of the project everything works _(e.g. error goes away and eslint errors are highlighted)_. See branch [`all-is-fine`](https://github.com/samit4me/use-alias-demo/tree/all-is-fine).

Other eslint rules appear to work regardless of where the code lives but if as soon as I add `module-resolver` to the plugins section of `.eslintrc` it throws an error when the code is nested in any directory other than the project root.

**Comment by HeroProtagonist** [comment] 2019-08-04 04:36
@samit4me thanks for all of this! I will take a look and hopefully have a fix soon.

**Comment by HeroProtagonist** [comment] 2019-08-05 18:57
@samit4me I did a test and added another plugin [here](https://github.com/samit4me/use-alias-demo/pull/1). The same error seems to be occurring with that plugin, so I am assuming this is unrelated to this plugin. I think it is an issue with the nested structure and the eslint extension. I might close this as the issue is not with the library. What do you think?

Also to be noted that libraries using a monorepo structure seem to place all the configuration files at the root level as seen with [babel](https://github.com/babel/babel)

**Comment by samit4me** [comment] 2019-08-05 20:55
Thanks for looking into this @HeroProtagonist 🙏.

I've had a quick look and it turns out that the vscode eslint plugin allows you to specify working directories ([docs here](https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint#settings-options)), so I tried adding the following: 
```
{
  "eslint.workingDirectories": ["./folderA/one"]
}
```
Then added the react plugin as per your example and 🎉 it appears work ([branch demo](https://github.com/samit4me/use-alias-demo/tree/react-plugin)):

![image](https://user-images.githubusercontent.com/3248531/62493585-d7269f00-b814-11e9-9574-3ca90a82f4b3.png)

**Unfortunately**, I am still getting the same issue with `module-resolver`, even with the update to `"eslint.workingDirectories"` ([example code here](https://github.com/samit4me/use-alias-demo/pull/new/react-and-module-resolver)). Not sure if it's somehow related to `babel-plugin-module-resolver` but the error shown below seems more related to eslint, but in saying that, I actually have no idea how any of this stuff works 😄. I am happy to investigate further, but it may take some time.
```
TypeError: Error while loading rule 'module-resolver/use-alias': Cannot read property 'plugins' of null
```

**Comment by samit4me** [comment] 2019-08-07 05:57
Attempted to solve this today and I may have found a solution _(as shown below)_, this worked in both VSCode and from terminal. I'll have to try more use cases and other OS _(only tried Ubuntu)_ but what's your initial thoughts? Happy for me to dig further and create a PR if it works.

`/lib/rules/use-alias.js`
From:
```JS
create: function(context) {
  const { config } = findBabelConfig.sync('.')
  const { options } = context
 ...
```

To:

```JS
create: function(context) {
  const [projectRoot] = path.resolve(__dirname).split("/node_modules");
  const pathToProjectRoot = `.${projectRoot.split(process.cwd())[1]}`;
  const { config } = findBabelConfig.sync(pathToProjectRoot)
  const { options } = context
  ...
```

**Comment by HeroProtagonist** [comment] 2019-08-07 23:42
@samit4me please do! Make sure tests still pass 👍

**Comment by HeroProtagonist** [comment] 2019-08-08 04:12
Would using the eslint [context](https://eslint.org/docs/developer-guide/working-with-rules#the-context-object) object and finding the config near the current file work? Context is used in a similar way [here](https://github.com/HeroProtagonist/eslint-plugin-module-resolver/blob/master/lib/rules/use-alias.js#L60)

**Comment by samit4me** [comment] 2019-08-08 15:13
Hi @HeroProtagonist, I had some time tonight so I got to work and testing my theory on Linux/Mac/Windows but unfortunately ran into issues on Windows.

The issue is that  `process.cwd()` is not reliable on Windows, as VS Code reports the install dir as the "working directory" if eslint not in the root.

I did take a look at eslint `context.getFilename()` but unfortunately that doesn't help find the project root (e.g. `folderA/one` in my demo).

Managed to find a solution using an absolute path (via `__dirname`) which `find-babel-config` supports and this appears to work on all platforms 🎉 The only problem I have though is getting all the tests passing (invalid test fail) 😞

The issue seems to be that because I am using `__dirname` and I have no idea how to mock it, so I have to deal with real directory paths. The problem with this is that I use `node_modules` to discovery the `projectRoot`, which is fine in a real environment (always inside `node_modules`), but in this testing environment this doesn't work. This has a knock on effect causing the `normalizedAliasArray` to be incorrect which in turn breaks the `isAliased` check.

Currently I've got no idea how to get around this, so probably need some time to think about it, but please take a look at what I've done and if you have any ideas they would be welcomed with open arms 🤗 

PR #16

**Closed** 2019-09-03 00:34 UTC
